name: Build and test

on:
  branches:
    - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: GIT--checkout
        uses: actions/checkout@v4

      - name: JAVA--set-up-jdk-17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'

      - name: MAVEN--build-and-test
        run: mvn -B package

