name: Release

on:
  push:
    tags:
      - 'v*.*.*'
      - 'v*.*.*-RC-*'

jobs:
  build:
    name: Build and release
    runs-on: ubuntu-latest
    steps:
      - name: GIT--checkout
        uses: actions/checkout@v4

      - name: JAVA--set-up-jdk-17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'

      - name: MAVEN--build-and-test
        run: mvn -B package

      - name: GIT--extract-release-version
        id: release
        if: success()
        run: |
          # Strip git ref prefix from version
          RELEASE_VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && RELEASE_VERSION=$(echo $RELEASE_VERSION | sed -e 's/^v//')

          # Strip build number suffix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && RELEASE_VERSION=$(echo $RELEASE_VERSION | sed -e 's/\+[0-9]*$//')

          echo $RELEASE_VERSION
          echo "version=$RELEASE_VERSION" >> $GITHUB_OUTPUT

      - name: GITHUB--create-release
        if: ${{ success() && startsWith(github.ref, 'refs/tags/') }}
        uses: softprops/action-gh-release@v2
        with:
          name: Version ${{ steps.release.outputs.version }}
          body_path: CHANGELOG.md
          make_latest: true
          files: |
            target/keycloak-tiktok-*.jar
