name: Release

on:
  push:
    tags:
      - 'v*.*.*'
      - 'v*.*.*-RC-*'

jobs:
  build:
    name: Build and release
    runs-on: ubuntu-latest
    steps:
      - name: GIT--checkout
        uses: actions/checkout@v4

      - name: JAVA--set-up-jdk-17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'

      - name: MAVEN--build-and-test
        run: mvn -B package

      - name: GITHUB--semantic-release
        if: success()
        id: semantic
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 23
          extra_plugins: |
            @semantic-release/changelog@6
            @terrestris/maven-semantic-release@2
            @semantic-release/git@10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
